### ISSUE TITLE
Da error

### ISSUE THREAD

**Issue by AlexCernik** [JesusJimenezG/platzidl#1]
El error es el siguiente 

Traceback (most recent call last):
  File "platzidl.py", line 200, in <module>
    main()
  File "platzidl.py", line 196, in main
    download_courses(courses)
  File "platzidl.py", line 141, in download_courses
    _platzidl(course)
  File "platzidl.py", line 130, in _platzidl
    _cli_request(command, logpath)
  File "platzidl.py", line 53, in _cli_request
    os.chdir(os.path.dirname(logpath))
FileNotFoundError: [Errno 2] No such file or directory: '-home-cernik-Desarrollo-React-plat-platzidl-Courses-1318-django-12571-como-conectar-django-a-una-base-de-datos'

**Comment by gersilva96** [comment]
Tengo exactamente el mismo error en Kubuntu 20.10

**Comment by JesusJimenezG** [comment]
El problema es debido a que cada `/` es reemplazado por un `-` al momento de crear los directorios en Windows. 

Las siguientes líneas deben ser modificadas en la funcion `def_platzidl(course)`


    `# OS parameters - Creates course path and sets current course directory
    coursepath = os.path.join(DLPATH,course)
    ####winpath = coursepath.replace('/',` '-') ### reemplazar cada winpath por coursepath
    if not os.path.exists(coursepath):
        os.mkdir(coursepath)
    os.chdir(coursepath)

    command = _get_youtube_dl_cli_command(course)
    
    # Execute command and log stdout/stderror
    logile = course + ".log"
    ####winlog = logile.replace('/', '-')#####de igual modo reemplazar winlog por logile
    logpath = os.path.join(coursepath,logile)
    _cli_request(command, logpath)`

Esto debería crear correctamente los directorios en Linux.

**Comment by ferchjs** [comment]
El error continua al menos en Arch:

```
Traceback (most recent call last):
  File "platzidl.py", line 197, in <module>
    main()
  File "platzidl.py", line 193, in main
    download_courses(courses)
  File "platzidl.py", line 139, in download_courses
    _platzidl(course)
  File "platzidl.py", line 128, in _platzidl
    _cli_request(command, logpath)
  File "platzidl.py", line 52, in _cli_request
    os.chdir(os.path.dirname(logpath))
FileNotFoundError: [Errno 2] No such file or directory: '-home-ferchjs-Downloads-platzidl-Courses-1318-django-12398-introduccion-al-curso5511'

```

**Comment by JesusJimenezG** [comment]
> El error continua al menos en Arch:
> 
> ```
> Traceback (most recent call last):
>   File "platzidl.py", line 197, in <module>
>     main()
>   File "platzidl.py", line 193, in main
>     download_courses(courses)
>   File "platzidl.py", line 139, in download_courses
>     _platzidl(course)
>   File "platzidl.py", line 128, in _platzidl
>     _cli_request(command, logpath)
>   File "platzidl.py", line 52, in _cli_request
>     os.chdir(os.path.dirname(logpath))
> FileNotFoundError: [Errno 2] No such file or directory: '-home-ferchjs-Downloads-platzidl-Courses-1318-django-12398-introduccion-al-curso5511'
> ```

sigue creando el directorio como "-home-ferchjs-" lo cual no es una ruta valida. La versión modificada para Linux ya está subida, prueba ejecutando ese script.

**Comment by ferchjs** [comment]
Continua el error pero ahora no es -home-fercjs- sino /home/ferchjs/
```
Traceback (most recent call last):
  File "linux-platzidl.py", line 195, in <module>
    main()
  File "linux-platzidl.py", line 191, in main
    download_courses(courses)
  File "linux-platzidl.py", line 137, in download_courses
    _platzidl(course)
  File "linux-platzidl.py", line 118, in _platzidl
    os.mkdir(coursepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ferchjs/Downloads/platzidl/Courses/1318-django/12398-introduccion-al-curso5511'
```
