### ISSUE TITLE
Descarga muy lenta

### ISSUE THREAD

**Issue by sasu08** [JesusJimenezG/platzidl#2]
Buenas! Primero que nada felicito al creador de este código porque nos hizo la vida cien veces mas fácil jajaja, el problema es que tengo una conexión de 300mb que descarga en promedio a 40mbps pero al utilizar el youtube-dl con suerte baja a 1mbps. Vi por ahí algo de usar Aria2 pero no tengo tanto conocimiento en Python como para tocar el código y probar. Alguna solución para arreglar esa limitación? a otros amigos con menor velocidad le descarga más lento aún.

**Comment by JesusJimenezG** [comment]
Dentro de platzidl.py  hay dos parámetros que puedes modificar:

 `RATE_LIMIT = "1M" ` es el límite de descarga. Puedes establecerlo en 4M.
`SLEEP_INTERVAL = 120` y `SLEEP_OFFSET = 50` son el tiempo de pausa entre descargas. Pueden ser modificados ambos a 5 dejando un máximo de 10 segundos de espera entre descargas.

Estos son parámetros preventivos del script [original](https://github.com/leethobbit/pluradl.py) hecho para descargar de Pluralsight. Hasta ahora Platzi no ha mostrado ningún inconveniente con el tiempo y número entre peticiones así que pueden ser modificados. No obstante recomiendo hacerlo con una cuenta gratuita creada solo para el PlatziDay.

**Comment by sasu08** [comment]
> Dentro de platzidl.py hay dos parámetros que puedes modificar:
> 
> `RATE_LIMIT = "1M" ` es el límite de descarga. Puedes establecerlo en 4M.
> `SLEEP_INTERVAL = 120` y `SLEEP_OFFSET = 50` son el tiempo de pausa entre descargas. Pueden ser modificados ambos a 5 dejando un máximo de 10 segundos de espera entre descargas.
> 
> Estos son parámetros preventivos del script [original](https://github.com/leethobbit/pluradl.py) hecho para descargar de Pluralsight. Hasta ahora Platzi no ha mostrado ningún inconveniente con el tiempo y número entre peticiones así que pueden ser modificados. No obstante recomiendo hacerlo con una cuenta gratuita creada solo para el PlatziDay.

Muchas gracias!! Nuevamente felicitaciones por tan buena automatización. Un saludo
