### ISSUE TITLE
Dónde queda youtube_dl??? Para poder agregarlo a las variables de entorno 

### ISSUE THREAD

**Issue by drfcozapata** [JesusJimenezG/platzidl#4]
Hola brother!

Me parece genial tu idea... Ya descargué todo es instalé youtube_dl con npm.
Pero no sé en qué directorio se encuentra para poder agregarlo ahora a las variables de entorno.
Se agrega al usuario o global????
Gracias de antemano... A ver si tu respuesta llega a tiempo que hay un curso que quiero. ;)

YA RESOLVÍ... GRACIAS!!! Está brutal este programa.

**Comment by Heiner1106** [comment]
Cuando uso el platzidl me sale este error en centos8

Traceback (most recent call last):
  File "./platzidl.py", line 197, in <module>
    main()
  File "./platzidl.py", line 193, in main
    download_courses(courses)
  File "./platzidl.py", line 139, in download_courses
    _platzidl(course)
  File "./platzidl.py", line 128, in _platzidl
    _cli_request(command, logpath)
  File "./platzidl.py", line 52, in _cli_request
    os.chdir(os.path.dirname(logpath))
FileNotFoundError: [Errno 2] No such file or directory: '-home-bits-Descargas-platzidl-Courses-1842-intro-laravel-27095-que-es-laravel-'

**Comment by ghost** [comment]
Es por que estas usando el script para Windows, por tal motivo el acceso a las rutas es diferente
