### ISSUE TITLE
New script for linux users

### ISSUE THREAD

**Issue by ghost** [JesusJimenezG/platzidl#5]
Debido a que el script para linux no funciono y tenia algunos fallos en cuanto a los directorios, reinvente un nuevo script que funciona de maravilla, ademas permite descargar los cursos en secciones.
Me gustaría que revisaran el nuevo script 'linux-platzidl-devil.py' y si te parece bien me dejaras unir el nuevo script a este proyecto.
link del fork: https://github.com/Devil64-Dev/platzidl

**Comment by JesusJimenezG** [comment]
> Debido a que el script para linux no funciono y tenia algunos fallos en cuanto a los directorios, reinvente un nuevo script que funciona de maravilla, ademas permite descargar los cursos en secciones.
> Me gustaría que revisaran el nuevo script 'linux-platzidl-devil.py' y si te parece bien me dejaras unir el nuevo script a este proyecto.
> link del fork: https://github.com/Devil64-Dev/platzidl

El script de Linux ya ha sido modificado y se ha solucionado dicho error. Teniendo en cuenta que es un script completamente diferente lo puedes compartir con los usuarios de Linux que presenten algún error que aún no tenga solución con el actual.
