### ISSUE TITLE
error al usarlo en Centos8

### ISSUE THREAD

**Issue by Heiner1106** [JesusJimenezG/platzidl#6]
al momento de ejecutar el archivo platzidl me sale este error, como podria solucionarlo
Traceback (most recent call last):
  File "./platzidl.py", line 197, in <module>
    main()
  File "./platzidl.py", line 193, in main
    download_courses(courses)
  File "./platzidl.py", line 139, in download_courses
    _platzidl(course)
  File "./platzidl.py", line 128, in _platzidl
    _cli_request(command, logpath)
  File "./platzidl.py", line 52, in _cli_request
    os.chdir(os.path.dirname(logpath))
FileNotFoundError: [Errno 2] No such file or directory: '-home-bits-Descargas-platzidl-Courses-1842-intro-laravel-27095-que-es-laravel-'

**Comment by ghost** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '-home-bits-Descargas-platzidl-Courses-1842-intro-laravel-27095-que-es-laravel-'
Prueba con el script que dice tiene el prefijo linux-, ya que el que ejecutas es para windows

**Comment by ghost** [comment]
Pero si aun despues de eso te falla algo prueba con este que reinvente basado en el existente para mi funciona: https://github.com/Devil64-Dev/platzidl

**Comment by Heiner1106** [comment]
Muchas Gracias really Works
